name: Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Install and Build 🔧
              run: |
                  npm ci
                  echo "VITE_MAPBOX_TOKEN=${{ secrets.VITE_MAPBOX_TOKEN }}" > .env
                  npm run build

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4.6.4
              with:
                  folder: dist # The folder the action should deploy.
